<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Serverbound</AssemblyName>
    <RootNamespace>Serverbound</RootNamespace>
    <Version>0.1.1</Version>
    <Title>Serverbound</Title>
    <Description>Dedicated world simulation and optional client compatibility for Valheim.</Description>
    <OutputPath>../../bin/$(Configuration)/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil"><HintPath>$(LabPath)/BepInEx/core/Mono.Cecil.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.Utils"><HintPath>$(LabPath)/BepInEx/core/MonoMod.Utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>$(LabPath)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(LabPath)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim" Publicize="true"><HintPath>$(ValheimManaged)\assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>$(ValheimManaged)\assembly_utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ValheimManaged)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ValheimManaged)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(ValheimManaged)\UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(ValheimManaged)\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(ValheimManaged)\UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(ValheimManaged)\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SoftReferenceableAssets" Publicize="true"><HintPath>$(ValheimManaged)/SoftReferenceableAssets.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(ValheimManaged)/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AssetBundleModule"><HintPath>$(ValheimManaged)/UnityEngine.AssetBundleModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="com.rlabrecque.steamworks.net"><HintPath>$(ValheimManaged)/com.rlabrecque.steamworks.net.dll</HintPath><Private>false</Private></Reference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all" ExcludeAssets="contentFiles" />
  </ItemGroup>
</Project>
